#!/usr/bin/env python3
"""
Regenerate alphax_pos_suite/spa_payload.py from the vendor asset tree.

Run after ANY change to files under alphax_pos_suite/public/dist/vendor:

    python build_spa_payload.py

Why this exists: the vendor tree lives at deep filesystem paths that
Windows tooling (git without core.longpaths, Explorer extraction) has
repeatedly failed to transport, twice deleting the tree from the repo
and bricking deployed registers. The payload file lives at a SHORT
path, so it survives any of those failure modes — and the server
self-heals the tree from it on migrate (see cashier/assets.py and
install.py).
"""
import base64
import hashlib
import io
import os
import zipfile

VENDOR = os.path.join("alphax_pos_suite", "public", "dist", "vendor")
OUT = os.path.join("alphax_pos_suite", "spa_payload.py")

buf = io.BytesIO()
count = 0
with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for root, _dirs, files in os.walk(VENDOR):
        for name in sorted(files):
            if name == ".payload_sha":
                # version stamp written below — never part of the payload,
                # or the stamp would change the digest it records
                continue
            full = os.path.join(root, name)
            rel = os.path.relpath(full, VENDOR).replace(os.sep, "/")
            z.write(full, rel)
            count += 1

raw = buf.getvalue()
b64 = base64.b64encode(raw).decode("ascii")
digest = hashlib.sha256(raw).hexdigest()

lines = [b64[i:i + 120] for i in range(0, len(b64), 120)]
joined = "\n".join(f'    "{l}"' for l in lines)

with open(OUT, "w") as f:
    f.write(f'''"""
AUTO-GENERATED by build_spa_payload.py — do not edit by hand.

Complete, compressed copy of alphax_pos_suite/public/dist/vendor
({count} files). This file lives at a SHORT path so it survives the
Windows long-path failures that have twice deleted the real tree from
the repo. cashier/assets.py serves from it as a last-resort root, and
install.py unpacks it to disk on migrate when the tree is missing.

sha256(zip) = {digest}
"""

FILE_COUNT = {count}
SHA256 = "{digest}"

_B64 = (
{joined}
)


def payload_bytes():
    import base64
    return base64.b64decode("".join(_B64))
''')

# Stamp the vendor tree with the digest of the payload built FROM it.
# install.py compares this stamp to spa_payload.SHA256 on every migrate:
# a mismatch means the on-disk tree and the payload diverged in transit
# (v15.7.4→.5 incident: git carried a stale payload while the tree was
# lost, so registers self-healed to OLD code and no browser refresh
# could ever fix it). On mismatch the payload — the single source of
# truth this script just built — is re-extracted over the tree.
with open(os.path.join(VENDOR, ".payload_sha"), "w") as f:
    f.write(digest + "\n")

size_kb = os.path.getsize(OUT) // 1024
print(f"spa_payload.py written: {count} files packed, {len(raw)//1024} KB zip, {size_kb} KB py, sha256={digest[:16]}…")
print("vendor/.payload_sha stamp written")
